services:

  nginx:
    image: nginx:alpine # alpine => more lightweight than the full nginx image
    container_name: nginx
    ports:
      - 80:80
      # - 443:443 # need to add SSL certificate and key
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./certs/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      # - ./certs/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    depends_on:
      - mia
      - warcraft3sounds
    restart: unless-stopped

  mia:
    build: ../mia
    container_name: mia
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - NODE_ENV=production
    volumes:
      - ${USER_PATH}/mia/data/:/root/mia/data/
      - ${USER_PATH}/mia/plugins/:/root/mia/plugins/

  warcraft3sounds:
    build: ../warcraft3sounds
    container_name: warcraft3sounds
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - NODE_ENV=production
    volumes:
      - ${USER_PATH}/warcraft3sounds/sounds/:/root/warcraft3sounds/sounds/
      - ${USER_PATH}/warcraft3sounds/logs/:/root/warcraft3sounds/logs/
